elifesciences/decision-letter-parser

letterparser/parse.py
tests/fixtures/dutzler_39122_sections.py
tests/fixtures/sections_sections.py

Follow-up to PR https://github.com/elifesciences/decision-letter-parser/pull/19, I want to use this more straight-forward data structure for the sections, where `section_type` is a key.

Change the sections data structure.

---

letterparser/build.py
letterparser/generate.py
letterparser/objects.py
letterparser/utils.py
requirements.txt
setup.py
tests/__init__.py
tests/fixtures/generate_simple.xml
tests/test_build.py
tests/test_generate.py
tests/test_objects.py

Here is a working example of building and generating JATS XML output. There are still todos in the `build.py` module. Test coverage is good using basic content for now.
I want to merge this into the develop branch of the pre-release of this library. It will allow me to generate some sample XML output on a new branch to allow for project scope to be estimated.

Generate branch

---

tox.ini

Follow-up to PR https://github.com/elifesciences/decision-letter-parser/pull/26, I forgot to remove py27 from tox tests.

Remove py27 tests from tox.

---

letterparser/generate.py
letterparser/utils.py
tests/fixtures/generate_simple.xml
tests/fixtures/kitchen_sink.xml
tests/helpers.py
tests/test_generate.py
tests/test_generate_kitchen_sink.py

Fixes https://github.com/elifesciences/decision-letter-parser/issues/22
The result of an experiment to take the content of `Article` objects and generate JATS XML like the eLife `00666` article kitchen sink XML. It is encapsulated in a test scenario which compares the output to an XML file fixture.
To make it work, 
- there are more whitelisted allowed tags, 
- added the `xlink` XML namespace, 
- `@id` attributes of tags are assigned,
- DOI is added to an `<article-id>` tag
- attributes of content block tags are added to the XML output (e.g. `<disp-quote content-type="editor-comment">`)

Kitchen sink XML generation

---

letterparser/docker_lib.py
letterparser/parse.py
letterparser/utils.py
requirements.txt
setup.py
tests/test_docker_lib.py
tests/test_parse.py
tests/test_utils.py

This library is a work-in-progress right now, so in order to compensate for when the `pandoc` executable is not available, fallback to calling pandoc from a Docker container.
The basics of this I tried in the unmerged https://github.com/elifesciences/decision-letter-parser/tree/pandoc-docker.
I have `pandoc` locally, which is not slowing me down, but eLife ci tests cannot run `pandoc` natively at this time.

Fallback, use docker for pandoc call.

---

project_tests.sh
tox.ini

Re issue https://github.com/elifesciences/decision-letter-parser/issues/6, I think this is one way so `coverage` is available when running tests. The travis-ci tests seem to not need this because `coveralls` is installed before `tox` is invoked.

Install coverage for project tests.

---

letterparser/parse.py
tests/test_parse.py

I planned to continue and improve the parsing and formatting of lists taken from `.docx` files. I tested converting a sample file I have, `Zaaijer 27798.docx`, which has some lists I was targetting, and it failed to build due to an XML parsing error.
I tracked down the cause to be more complicated situations where the break tag conversion function left open `<italic>` tags without a close tag in the new paragraphs. There are two types, added as test cases here.
The first is where the count of open and close tags is equal, causing the function to not open and close tags effectively.
The second, also from this same `.docx` file, is where a paragraph has an open `<italic>` tag, but then multiple `<break /><break />` tags before it closes it with the `</italic>` tag.
I also changed the …

More break tag conversion cases, code changes.

---

letterparser/build.py
letterparser/parse.py
tests/test_build.py
tests/test_parse.py

Testing locally with `Zaaijer 27798.docx` file, these are some improvements after comparing the output line by line, looking for any data omitted, or anything strange. Not too much, just a couple things here: replace italic break tags, and use the content inside `<disp-quote>` tags, because `<disp-quote>` later will have a new significance.

Tweaks to clean up italic and disp-quote

---

letterparser.cfg
letterparser/build.py
letterparser/conf.py
letterparser/docker_lib.py
letterparser/generate.py
letterparser/parse.py
letterparser/utils.py
requirements.txt
setup.py
tests/test_build.py
tests/test_conf.py
tests/test_docker_lib.py
tests/test_generate.py
tests/test_parse.py
tests/test_parse_list.py
tests/test_parse_sections.py
tests/test_parse_strike_through.py
tests/test_parse_table.py
tests/test_utils.py

Fixes https://github.com/elifesciences/decision-letter-parser/issues/34
Fixes https://github.com/elifesciences/decision-letter-parser/issues/29
Related to the config ticket https://github.com/elifesciences/decision-letter-parser/issues/43
This introduces a `letterparser.cfg` config file to hold some configuration details, a `conf.py` module to parse those values, and pass the config around to functions that use it.
How the five-digit manuscript number for eLife is parsed from file names will change soon when a `.zip` file convention is added in the coming days.

Library config file

---

letterparser.cfg
letterparser/docker_lib.py

Small changes to use the official pandoc Docker image. The existing tests pass for me when using the pandoc version 2.6 image. If all green, I will switch over to this for going forward, because the image size is smaller on disk.

Switch to official pandoc Docker image.

---

letterparser.cfg
letterparser/build.py
letterparser/utils.py
tests/fixtures/kitchen_sink.xml
tests/test_build.py
tests/test_generate_kitchen_sink.py
tests/test_utils.py

These are some accumulated changes from attempting to generate XML output like the kitchen sink XML file from a composed `.docx` file. The `.docx` file is not finished yet -- almost.
I do not want to lose these fixes and I may switch over to the parsing of a few remaining content pieces before I finish the `.docx` file. Since disp-quote tags and table parsing are not done yet, it is not possible generate the full kitchen sink XML yet without more code.
I think existing test cases are largely unchanged here. These changes are based on parsing real `.docx` files and seeing what breaks and what is missing or wrong.

Tweaks and fixes from creating kitchen sink XML

---

letterparser/parse.py

Fixes #52. If no config is used, or the value of the docker image is not specified, then use a default Docker image.

Specify default docker image for running pandoc.

---

letterparser/build.py
tests/test_build.py

For eLife article samples, a paragraph that is entirely italic in the author reponse corresponds with a `<disp-quote content-type="editor-comment">` XML element in the output. This PR makes that happen.
It further expanded using the `wrap` logic, making it more complicated and confusing, so this also includes refactoring of the code into separate functions. As well, tracking previous content uses a standard dict of values for clarity and reducing the number of arguments.

disp-quote editor comment

---

letterparser/build.py
tests/test_build.py

Fixes https://github.com/elifesciences/decision-letter-parser/issues/17
The original issue had a more lengthy list of tasks, some of them I moved to a new issue to do as subsequent enhancements. Included here are just the basics of adding a `<table-wrap>`, `<label>`, `<caption><title>`, and the `<table>` itself, with minimal alteration.
Includes some refactoring of how label and title is detected so the logic can be shared between fig and table-wrap tags.

Basic table

---

letterparser/generate.py
letterparser/utils.py
tests/fixtures/kitchen_sink.xml
tests/test_generate.py
tests/test_generate_kitchen_sink.py
tests/test_utils.py

After some experimentation and a slight rework, this is an example of adding `<xref>` tags around mentions of assets in a paragraph. It seems to be stable enough across the tests and files I'm testing with so far.
The challenge came up because you cannot replace a tag in an`ElementTree`, but I didn't want to try using the standard XML editing route, that would require checking `text` and `tail`, and trying to edit existing tags. For this reason, I continued with the original plan of converting XML -> string, adding the `<xref>` tag with regular expressions, then parsing the string -> XML again. Once inserting the tag into the parent tag and removing the old tag was working, this seems ok for now.
I expanded `open_tag()` to optionally accept tag attributes.
The terms to match come from …

xref tag wrapping logic

---

letterparser/build.py
tests/test_build.py

Found when integrating this into a real workflow, being able to get the `Article.manuscript` property will come in handy. When building the sub article object, set this property to the value that was passed in.

Set Article.manuscript value in build_sub_article.

---

letterparser/generate.py
tests/test_build.py
tests/test_build_articles.py
tests/test_build_content_sections.py
tests/test_generate.py

An edge case in data for article `50209` used as a test uncovered a bug in the logic that adds `<xref>` tags in paragraph content where image or video labels are mentioned.
Here is the code fix and a new, elaborate test scenario that grew out of trying to debug it.
If tests are green I will merge.
Note, I also refactored some existing tests into separate files while I tried to track down where the bug was happening.

Fix block order when xref tags are added

---

letterparser/build.py
tests/test_build_content_sections.py

A bug observed when testing on a modified sample (based on an early sample named `eLife-23456.docx`). When there was a table preceeded by a regular paragraph, the table was repeated along with the content from the paragraph after the table.
This is a code fix for the `build.py` module and a test case is included for the situation.

Edge case fix table parsing and paragraph append.

---

letterparser/utils.py
tests/test_utils.py

Re issue https://github.com/elifesciences/issues/issues/5557
An issue with article `53580` decision letter where new line characters in the pandoc JATS output  immediately after an Author response section heading causes a parsing error.
This should be an isolated situation that will not have side effects, hopefully.

Fix edge case collapsing new line on section name.

---

letterparser/utils.py
tests/test_utils.py

A bug in article `54519` input made visible an improvement to the logic that collapses new line characters into paragraphs. This satisfies existing tests, and new test cases make that coverage more easily testable in the future.

Improve collapsing new lines logic.

---

letterparser/utils.py
tests/test_utils.py

Re issue https://github.com/elifesciences/issues/issues/5610
An edge case observed where a new line character is prior to a bold **Author response** section heading. This will insert the `<break /><break />` in place of the new line character in this example. It again doesn't conflict with any existing test cases, and it is hopefully going in the right logical direction, where these edge cases will eventually all be collected and fixed.

Edge case new line replace for Author response.

---

letterparser/parse.py
tests/test_convert_break_tags.py

Re issue https://github.com/elifesciences/issues/issues/5618
When converting break tags, there is an edge case for when content ends in `</disp-quote>` then do not add a `</p>` tag.

Fix convert break tags ending in </disp-quote>

---

letterparser/build.py
tests/test_build_content_sections.py

Re issue https://github.com/elifesciences/issues/issues/5622
An article `.docx` has two simple fig in a row, and this is a fix for when fig wrap are in succession.

Fix parsing more than one simple fig in a row.

---

letterparser/utils.py
tests/test_utils.py

Re issue https://github.com/elifesciences/issues/issues/5676 described a couple of example articles where the new line characters were not split into paragraphs correctly, and sometimes there was also extra italic tags.
Code in this PR seems to fix these two errors, and it doesn't conflict with any existing test scenarios in the project. Hopefully these will be an improvement and not introduce new bugs into the parsing procedure.
There are a couple more additional glitches yet to fix, but it can be done separately, since they're not figured out yet.

Fixes for collapsing new lines from recent articles

---

letterparser/generate.py
letterparser/utils.py
tests/test_utils.py

Re issue https://github.com/elifesciences/issues/issues/5696
Previously, there was only one XML which produced duplicate XML namespaces on the root tag when converted to a string. Today there was another, this time the `xmlns:xlink` namespace was the one duplicated.
Here, rather than accumulating each specific example of duplicate namespaces we observe, the logic is changed to programatically analyse the root tag attributes, de-duplicate the values, and replace the old tag string with the new tag string, as it did before.

More adaptive XML namespace de-dupe logic.

---

letterparser/build.py
tests/test_build_match.py

Fixes https://github.com/elifesciences/issues/issues/5767
A fairly straightforward bug when a `.docx` contained `Author response image 10`, and the matching pattern was only set to handle one digit in the numbering. Here, fix the match patterns to match any number.
I added a couple test cases, not for all the match patterns, but enough I hope to confirm it continues to function and is easy to diagnose errors.

Label string match for numbers greater than nine.

---

letterparser/build.py
tests/test_build_content_sections.py

Fixes https://github.com/elifesciences/issues/issues/5768
Includes a simple solution for if a fig has no caption, then the next non-caption paragraph test if it should be an editor comment `disp-quote` tag or not.
There is possibly some space for refactoring, where it could also check if the next paragraph is a table or a video, but until we see that case, this is a simple solution based on real data we've observed.

Improve parsing fig with no caption followed by disp-quote

---

letterparser/build.py
tests/test_build_content_sections.py

Re issue https://github.com/elifesciences/issues/issues/5821
Previously, the only way to denote a table in the `.docx` file was to start with a bold paragraph like this:
**Author response table 1**
The designators for a figure or video, however, are enclosed in brackets, like:
`<Author response figure 1>`
The code here adds bracketed table mentions, and continues to support bold table mentions. So now this will also be allowed:
`<Author response table 1>`
The optional title/legend tagging remains the same, because for all assets that those tokens were always using brackets around them.
I added test scenarios for all the new possible situations so if the tests are green I will merge and deploy it ASAP.

Support bracketed table labels too.

---

letterparser/utils.py
tests/test_utils.py

Re issue https://github.com/elifesciences/issues/issues/5848, where another collapse new lines edge case was observed, and this PR fixes the situation.

Fix collapse new line before bold section heading.

---

letterparser/generate.py
tests/test_generate.py

Re issue https://github.com/elifesciences/issues/issues/5795
The existing logic to add `<xref>` tags around mentions of figures in paragraph text was only surrounding terms that matched the label value exactly (not counting any full stop at the end, which is stripped before looking for matches). If a mention of specific figure panels appeared in the text, the `<xref>` tag did not expand to included the alphabetical-optionally-hyphenated panel term. 
E.g. "Author response image 1C-F" instead of
```xml
<xref ref-type="fig" rid="sa2fig1">Author response image 1</xref>C-F
```
we will now get
```xml
<xref ref-type="fig" rid="sa2fig1">Author response image 1C-F</xref>
```
Code includes refactoring to make these parts easier to understand and to test, and there are test cases based on some real …

Enhancements to asset xref tagging

---

letterparser/build.py
letterparser/generate.py
tests/test_build.py
tests/test_generate.py

Re issue https://github.com/elifesciences/issues/issues/5874
A recent article failed to generate XML from the `.docx` file, the reasons centred around a figure caption, how it was parsed, and how the asset xref tag highlighting logic was confused by trying to search for a blank figure label in paragraph text.
Code here includes the fixes and two test cases for these situations.

Caption parsing fix and asset xref tag fix

---

letterparser/build.py
tests/test_build_content_sections.py

Re issue https://github.com/elifesciences/issues/issues/6050
A situation observed where a figure with no legend is immediately followed by a table. The code changes here will detect those properly, as well as any video followed immediately by a table.

Fix for fig with no legend followed by a table.

---

letterparser/parse.py
tests/test_convert_break_tags.py

Re issue https://github.com/elifesciences/issues/issues/6212
As example of a list block in an article where the function that processes break tags is erroneously adding a `</p>` tag. The fix here is to not do that if the content ends in a `</list>` tag.

Do not </p> after </list> in convert break tags.

---

letterparser/build.py
tests/test_build_match.py

A result of issue https://github.com/elifesciences/issues/issues/5825 where a kitchen sink docx file is being finalised, this code will allow an optional full stop to be included in the angle bracketed mentions in the docx file. The full stop will carry through into the XML output in the `<label>` tag.

Allow a full stop at end of asset names.

---

tests/fixtures/elife-00666.xml
tests/test_generate.py

Re issue https://github.com/elifesciences/issues/issues/5825
Here the `.docx` kitchen sink is inside the `elife-00666.zip` test data file, along with assets to match the figures and video found there, in a test case is show to generate and match exactly the `elife-00666.xml` output. The kitchen sink `.docx` contains many, if not all, of the content elements supported by the parser.
Thanks for @FAtherden-eLife for helping to put together the final document and zip package!

Kitchen sink docx file and XML fixture for test scenario

---

letterparser/utils.py
tests/test_build.py
tests/test_build_content_sections.py
tests/test_build_match.py
tests/test_utils.py

Re bug issue https://github.com/elifesciences/issues/issues/6581
eLife article `64740` decision letter had a bug parsing an author response editor comment paragraph containing inline formulae. The cause looked like due to a new line character prior to the italic paragraph was not considered to be a paragraph break in the decision letter parser logic, and as a result the italic paragraph was appended to the previous paragraph's content.
The code fix in this PR is in the `utils.py` module, and then there are some additional test scenarios added related to the bug. In addition, some tests for the `match_disp_quote_content()` function are a bonus, since as part of the troubleshooting process, it was tested more extensively.
There are no backwards compatibility problems anticipated in this PR, …

Fix new line break for italic tag on its own line.

---

letterparser/utils.py
tests/test_utils.py

Re bug issue https://github.com/elifesciences/issues/issues/6611
A decision letter had bold style removed from the `Decision letter` heading, which caused that section to be unrecognised. After investigation, it seemed like we can try to not remove the complex script style tags from the `.docx` file when it is "repaired" if the run contains a specific type of font tag.
In the end, the simplest solution was also the fastest: split the docx file's `word/document.xml` contents on each run tag (`<w:r>`), and then remove the complex script style tags on a run-by-run basis.

Enhance removal of complex scripts styles tags.

---

letterparser/parse.py
letterparser/utils.py
tests/test_utils.py

Re issue https://github.com/elifesciences/issues/issues/6751
Parsing a `.docx` file resulted in an error when trying to match a table heading in the content. A line in the `.docx` file contained a single non-breaking space character, which resulted in a `<p> </p>` blank paragraph, and if it appears immediate after a table heading, then the current table matching pattern fails. Example content,
```xml
<p><bold>Author response table 1.</bold> </p>
<p> </p>
```
This PR adds an additional utils function, `remove_empty_p_tags()`, to remove any paragraphs which only contain whitespace, assuming these are unintentional and do not add any value to the output at this time.

Remove p tags which only contain whitespace.

---

Jenkinsfile.release
README.md
requirements.txt
setup.py

First attempt at configuring the library release pipeline, this will next go into the `master` branch, and then to configure the Jenkins pipeline.
Use server versioned libraries in the requirements.txt
Updated `setup.py` with the `long_description_content_type` value and linted it
Updated the readme
Added `Jenkinsfile.release`

Release pipeline configuration
